### ISSUE TITLE
The total hits counter is never updated

### ISSUE THREAD

**Issue by nikneem** [nikneem/shortlink-core#2]
The total hits counter on a shortlink is never updated when a hit is received from the EventBus

**Comment by atrievel** [comment]
@nikneem - I'd be happy to take this on. Could you maybe provide some insight as to which method this needs to be implemented in (I'm assuming UpdateExistingShortLinkAsync in the SortLink Repository) and any coding styles/standards you'd like for me to follow? Thanks in advance

**Comment by nikneem** [comment]
Hi, and thanks!
This core project is basically a NuGet repo used by an Azure Functions project. The functions project is not triggered by an event received from the EventBus with the time, and shotcode of a hit. Now, the hits are stored in a separate table and processed later on by timer triggered functions.
This is expected (and wanted) behavior, because these timer triggered functions make hourly and daily hits aggregates.

To stay in line with the current architecture I think the best solution is to create a HitsService with a ProcessHitAsync accepting a DateTimeOffset and the shortcode.

This service makes a call to a new IHitsRepository and creates a new Hit entry like the Azure Function does:
```csharp
            var entity = new HitEntity
            {
                PartitionKey = PartitionKeys.Hit,
                RowKey = Guid.NewGuid().ToString(),
                CreatedOn = events.ClickedAt,
                ShortCode = events.Key,
                Timestamp = DateTimeOffset.UtcNow
            };

            var operation = TableOperation.Insert(entity);
            await table.CreateIfNotExistsAsync();
            await table.ExecuteAsync(operation);
```


This service then makes a call to the existing shortcode repository, but using a new method (something like IncreaseHitCountAsync() or something accepting the shortcode.
